/*
 * ChatPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui.chat.panel;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.List;

import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.ui.chat.ChatClient;
import com.ui.chat.ChatClient.IChatClientActionListener;
import com.ui.chat.ChatClient.IChatServerActionListener;
import com.ui.chat.bean.CustomerBean;

/**
 * @author jim_qiao
 * 
 */
public class ChatClientPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 5829332834364826937L;

	/** Creates new form ChatPanel */
	private ChatClient client;
	private JFileChooser chooser;
	private JFrame frame;
	private IChatClientActionListener clientAction;

	public ChatClientPanel(final JFrame frame, String name, String serverHost) {
		initComponents();
		this.frame = frame;
		chooser = new JFileChooser(".");
		main.setAutoscrolls(true);
		client = new ChatClient(name, serverHost, new IChatServerActionListener() {

			@Override
			public void displayUserList(List<CustomerBean> list) {
				final List<CustomerBean> customers = list;
				userList.setModel(new AbstractListModel() {
					public int getSize() {
						return customers.size();
					}

					public Object getElementAt(int i) {
						return customers.get(i).getName();
					}
				});
			}

			@Override
			public void displayTextMessage(String text) {
				main.append(text + "\n\n");
			}

			@Override
			public void displayDebug(String debug) {
				debugMainArea.append(debug + "\n");
			}

			@Override
			public void displayFile(File file) {

			}

			@Override
			public void displaySize(int size) {
				// TODO Auto-generated method stub
				sizePb.setValue(size);
			}

			@Override
			public File requestSendFile(String ip, String name, String fileName, long size) {
				// TODO Auto-generated method stub
				String msg = MessageFormat.format("是否接收{0}发来的文件:{1},大小:{2}KB", name, fileName, size / 1024);
				int result = JOptionPane.showConfirmDialog(frame, msg);
				File file = null;
				if (result == JOptionPane.OK_OPTION) {
					result = chooser.showDialog(frame, "保存");
					if (result == JFileChooser.APPROVE_OPTION) {
						file = chooser.getSelectedFile();
						sizePb.setMaximum((int) size);
					}
				}
				return file;
			}
		});
		clientAction = client.getClientAction();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jToolBar1 = new javax.swing.JToolBar();
		sendFileBtn = new javax.swing.JButton();
		refresh = new javax.swing.JButton();
		sizePb = new javax.swing.JProgressBar();
		jSplitPane1 = new javax.swing.JSplitPane();
		jScrollPane3 = new javax.swing.JScrollPane();
		userList = new javax.swing.JList();
		jScrollPane1 = new javax.swing.JScrollPane();
		main = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		inputMsgArea = new javax.swing.JTextArea();
		sendBtn = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		debugMainArea = new javax.swing.JTextArea();
		jToolBar2 = new javax.swing.JToolBar();
		cleanDebugBtn = new javax.swing.JButton();

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);

		sendFileBtn.setText("Send File");
		sendFileBtn.setFocusable(false);
		sendFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		sendFileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		sendFileBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendFileBtnActionPerformed(evt);
			}
		});
		jToolBar1.add(sendFileBtn);

		refresh.setText("\u5237\u65b0");
		refresh.setFocusable(false);
		refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		refresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		refresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				refreshActionPerformed(evt);
			}
		});
		jToolBar1.add(refresh);
		jToolBar1.add(sizePb);

		jSplitPane1.setDividerLocation(100);
		jSplitPane1.setDividerSize(10);

		userList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(userList);

		jSplitPane1.setLeftComponent(jScrollPane3);

		main.setColumns(20);
		main.setEditable(false);
		main.setRows(5);
		jScrollPane1.setViewportView(main);

		jSplitPane1.setRightComponent(jScrollPane1);

		inputMsgArea.setColumns(20);
		inputMsgArea.setRows(5);
		inputMsgArea.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				inputMsgAreaKeyReleased(evt);
			}
		});
		jScrollPane4.setViewportView(inputMsgArea);

		sendBtn.setText("\u53d1\u9001");
		sendBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE).addComponent(jSplitPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE).addGroup(
						jPanel1Layout.createSequentialGroup().addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE,
								453, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305,
						Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
						jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(
										sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(jScrollPane4))));

		jTabbedPane1.addTab("main", jPanel1);

		debugMainArea.setColumns(20);
		debugMainArea.setEditable(false);
		debugMainArea.setRows(5);
		jScrollPane5.setViewportView(debugMainArea);

		jToolBar2.setFloatable(false);
		jToolBar2.setRollover(true);

		cleanDebugBtn.setText("Clean");
		cleanDebugBtn.setFocusable(false);
		cleanDebugBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		cleanDebugBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		cleanDebugBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cleanDebugBtnActionPerformed(evt);
			}
		});
		jToolBar2.add(cleanDebugBtn);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE).addComponent(jScrollPane5,
						javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
						javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane5,
						javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)));

		jTabbedPane1.addTab("debug", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1,
				javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE));
	}// </editor-fold>

	// GEN-END:initComponents

	private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		sendTextMsg();
	}

	private void refreshActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		clientAction.refresh();
	}

	private void cleanDebugBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		debugMainArea.setText("");
	}

	private void inputMsgAreaKeyReleased(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_ENTER) {
			sendTextMsg();
		}
	}

	private void sendFileBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int result = chooser.showDialog(this, "发送");
		if (result == JFileChooser.APPROVE_OPTION) {
			File file = chooser.getSelectedFile();
			try {
				clientAction.sendFile(file);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

	public void sendTextMsg() {
		String msg = inputMsgArea.getText().trim();
		if (msg.equals("")) {
			return;
		}
		clientAction.sendTextMessage(msg);
		inputMsgArea.setText("");
	}

	public void sendExitMsg() {
		client.sendExitMsg();
	}

	public void connect() {
		client.connect();
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton cleanDebugBtn;
	private javax.swing.JTextArea debugMainArea;
	private javax.swing.JTextArea inputMsgArea;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JToolBar jToolBar2;
	private javax.swing.JTextArea main;
	private javax.swing.JButton refresh;
	private javax.swing.JButton sendBtn;
	private javax.swing.JButton sendFileBtn;
	private javax.swing.JProgressBar sizePb;
	private javax.swing.JList userList;
	// End of variables declaration//GEN-END:variables

}