/*
 * ChatSettingPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui.chat.panel;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

import com.ui.chat.frame.ChatClientFrame;

/**
 * 
 * @author __USER__
 */
public class ChatSettingPanel extends javax.swing.JPanel {

	/** Creates new form ChatSettingPanel */
	private JFrame frame;
	public ChatSettingPanel(JFrame frame) {
		this.frame = frame;
		initComponents();
		String[] ips = new String[254];
		for (int i = 0; i < ips.length; i++) {
			ips[i] = "" + i;
		}
		ip1.setModel(new DefaultComboBoxModel(ips));
		ip2.setModel(new DefaultComboBoxModel(ips));
		ip3.setModel(new DefaultComboBoxModel(ips));
		ip4.setModel(new DefaultComboBoxModel(ips));
		ip1.setSelectedIndex(192);
		ip2.setSelectedIndex(168);
		ip3.setSelectedIndex(1);
		ip4.setSelectedIndex(101);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		nameTxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		nextBtn = new javax.swing.JButton();
		exitBtn = new javax.swing.JButton();
		ip1 = new javax.swing.JComboBox();
		ip2 = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ip3 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		ip4 = new javax.swing.JComboBox();

		jLabel1.setText("Name:");

		jLabel2.setText("Server IP:");

		nextBtn.setText("Next");
		nextBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextBtnActionPerformed(evt);
			}
		});

		exitBtn.setText("Exit");
		exitBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitBtnActionPerformed(evt);
			}
		});

		ip1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		ip2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel3.setText(".");

		jLabel4.setText(".");

		ip3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel5.setText(".");

		ip4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addComponent(exitBtn).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nextBtn)).addGroup(
								layout.createSequentialGroup().addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(
												jLabel1).addComponent(jLabel2)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(
												layout.createSequentialGroup().addComponent(ip1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(ip2, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
																jLabel4).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
																ip3, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
																jLabel5).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
																ip4, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(nameTxt))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
								.addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(ip1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3).addComponent(ip2,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel4).addComponent(ip3,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2).addComponent(jLabel5)
										.addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE).addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nextBtn)
										.addComponent(exitBtn)).addContainerGap()));
	}// </editor-fold>

	// GEN-END:initComponents

	private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		final String ip = ip1.getSelectedItem() + "." + ip2.getSelectedItem() + "." + ip3.getSelectedItem() + "."
				+ ip4.getSelectedItem();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChatClientFrame(nameTxt.getText().trim(), ip).setVisible(true);
			}
		});
		frame.dispose();
	}

	private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton exitBtn;
	private javax.swing.JComboBox ip1;
	private javax.swing.JComboBox ip2;
	private javax.swing.JComboBox ip3;
	private javax.swing.JComboBox ip4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField nameTxt;
	private javax.swing.JButton nextBtn;
	// End of variables declaration//GEN-END:variables

}