/*
 * TableFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.swing;

import java.net.URL;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import com.util.Manager;
import com.util.RDeskTopLock;

/**
 * 
 * @author __USER__
 */
public class DeskTopLockFrm extends javax.swing.JFrame {

	/** Creates new form TableFrm */
	Manager m;
	public static final String STR_TIME = "time";
	public static final String STR_DELAY = "delay";
	public static final String STR_SIZE = "size";

	String confFileName = "DeskTopLock.ini";
	int time = 1000 * 15;
	int delay = 1000;
	int size = 5;

	public DeskTopLockFrm() {
		initComponents();
		try {
			m = new Manager(confFileName);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
		if (m.getValue(STR_TIME) != null)
			time = Integer.parseInt(m.getValue(STR_TIME));
		if (m.getValue(STR_DELAY) != null)
			delay = Integer.parseInt(m.getValue(STR_DELAY));
		if (m.getValue(STR_SIZE) != null)
			size = Integer.parseInt(m.getValue(STR_SIZE));
		txtTime.setValue(time);
		txtDelay.setValue(delay);
		txtSize.setValue(size);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnStart = new javax.swing.JButton();
		txtTime = new javax.swing.JSpinner();
		txtDelay = new javax.swing.JSpinner();
		txtSize = new javax.swing.JSpinner();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		btnStart.setText("start");
		btnStart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStartActionPerformed(evt);
			}
		});

		txtTime.setRequestFocusEnabled(false);

		jLabel1.setText("time");

		jLabel2.setText("delay");

		jLabel3.setText("size");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														txtTime,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														66,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														txtDelay,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														66,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		txtSize,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		66,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btnStart))
												.addComponent(jLabel3))
								.addContainerGap(17, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2)
												.addComponent(jLabel1)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtTime,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtDelay,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														20,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtSize,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnStart))
								.addContainerGap()));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		int time = Integer.parseInt(txtTime.getValue().toString());
		int delay = Integer.parseInt(txtDelay.getValue().toString());
		int addPointSize = Integer.parseInt(txtSize.getValue().toString());
		m.setValue(STR_TIME, "" + time);
		m.setValue(STR_DELAY, "" + delay);
		m.setValue(STR_SIZE, "" + addPointSize);
		try {
			m.saveFile(confFileName);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage());
		}
	}

	private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {
		int time = Integer.parseInt(txtTime.getValue().toString());
		int delay = Integer.parseInt(txtDelay.getValue().toString());
		int addPointSize = Integer.parseInt(txtSize.getValue().toString());
		RDeskTopLock topLock = new RDeskTopLock(time);
		topLock.setDelay(delay);
		topLock.setAddPointSize(addPointSize);
		new Thread(topLock).start();

		txtTime.setEnabled(false);
		txtDelay.setEnabled(false);
		txtSize.setEnabled(false);
		btnStart.setEnabled(false);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeskTopLockFrm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnStart;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JSpinner txtDelay;
	private javax.swing.JSpinner txtSize;
	private javax.swing.JSpinner txtTime;
	// End of variables declaration//GEN-END:variables

}
