/*
 * ChatClientFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui.chat.frame;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import com.ui.chat.panel.ChatClientPanel;

/**
 * @author jim_qiao
 * 
 */
public class ChatClientFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1544341591019725816L;

	/** Creates new form ChatClientFrame */
	final ChatClientPanel clientPanel;

	public ChatClientFrame(String name, String serverHost) {
		initComponents();
		clientPanel = new ChatClientPanel(this, name, serverHost);
		setTitle("ChatClientFrame 8888");
		setLayout(new BorderLayout());
		add(clientPanel, BorderLayout.CENTER);
		setLocationRelativeTo(null);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				clientPanel.sendExitMsg();
			}
		});
		clientPanel.connect();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChatClientFrame(null, "127.0.0.1").setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}