/*
 * ChatSettingFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui.chat.frame;

import java.awt.BorderLayout;

import com.ui.chat.panel.ChatSettingPanel;

/**
 * 
 * @author __USER__
 */
public class ChatSettingFrame extends javax.swing.JFrame {

	/** Creates new form ChatSettingFrame */
	public ChatSettingFrame() {
		initComponents();
		ChatSettingPanel panel = new ChatSettingPanel(this);
		setTitle("Chat setting");
		setLayout(new BorderLayout());
		add(panel, BorderLayout.CENTER);
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 429,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 208,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChatSettingFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}